# Generated by Django 3.2.9 on 2021-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Имя')),
                ('sex', models.IntegerField(choices=[(0, 'М'), (1, 'Ж')])),
                ('date_of_probe', models.DateField(verbose_name='Дата забора')),
                ('virus_load', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Вирусная нагрузка')),
                ('region', models.CharField(max_length=1024, verbose_name='Регион')),
                ('mutations', models.ManyToManyField(null=True, to='core.Mutations')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
