# Generated by Django 3.2.9 on 2021-11-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата забора'),
        ),
        migrations.AddField(
            model_name='patient',
            name='loyalty',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Приверженность*'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(0, 'М'), (1, 'Ж')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='virus_load',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вирусная нагрузка'),
        ),
    ]
