# Generated by Django 3.2.9 on 2021-12-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211130_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='loyalty',
            field=models.IntegerField(blank=True, default=100, max_length=1024, null=True, verbose_name='Приверженность*'),
        ),
    ]
